################################################################################
#   CONFIGURATIONS FOR HYPERPARAMETERS TUNING WITH TWO-STAGE AGGREGATE KERNEL RIDGE REGRESSION
################################################################################

# DATASET
dataset:
  # Path to main model data .nc file
  path: data/all_aod_global_updated_ds_06_06_2008.nc

  # Variables to use as 2D covariates
  2d_covariates:
    - burden_DMS
    - burden_SO2
    - burden_H2SO4
    - burden_SO4
    - burden_BC
    # - burden_OC
    # - burden_SS
    # - burden_DU
    # - burden_WAT
    # - abso4

  # Variables to use as 3D covariates
  3d_covariates:
    - ATTBETA_TOT_SPACE_533nm
    - relhum

  # Variable to use as 2D aggregate target
  target: ALFA_AER_533nm_2D

  # Variable corresponding to unobserved groundtruth 3D field
  groundtruth: ALFA_AER_533nm



# MODEL SPECIFICATIONS
model:
  # Matern kernel parameter for stage 1
  nu_2d: 1.5

  # Number of random fourier features samples for stage 1
  num_samples_2d: 500

  # Matern kernel parameter for stage 2
  nu_3d: 1.5

  # Number of random fourier features samples for stage 2
  num_samples_3d: 500

  # RFF sampling seed
  seed: 42



# GRID SEARCH
search:
  # Number of cross-validation splits to use
  n_splits: 5

  # Search grid
  grid:
    # Kernel lengthscales for stage 1
    lengthscale_2d:
      - 1
      - 10

    # L2 regularization weight for stage 1
    lbda_2d:
      - 0.1
      - 1

    # Kernel lengthscales for stage 2
    lengthscale_3d:
      - 1
      - 10

    # L2 regularization weight for stage 2
    lbda_3d:
      - 0.1
      - 1



# EVALUATION
evaluation:
