################################################################################
#   CONFIGURATIONS FOR VERTICAL DISAGGREGATION EXPERIMENT WITH TWO-STAGE AGGREGATE RIDGE REGRESSION
################################################################################

# DATASET
dataset:
  # Path to main model data .nc file
  path: data/all_aod_global_updated_ds_06_06_2008.nc

  # Variables to use as 2D covariates
  2d_covariates:
    - burden_DMS
    - burden_SO2
    - burden_H2SO4
    - burden_SO4
    - burden_BC
    # - burden_OC
    # - burden_SS
    # - burden_DU
    # - burden_WAT
    # - abso4

  # Variables to use as 3D covariates
  3d_covariates:
    - ATTBETA_TOT_SPACE_533nm
    - relhum

  # Variable to use as 2D aggregate target
  target: ALFA_AER_533nm_2D

  # Variable corresponding to unobserved groundtruth 3D field
  groundtruth: ALFA_AER_533nm


# GRID SEARCH
search:
  # Number of cross-validation splits to use
  n_splits: 5

  # Search grid
  grid:
    # L2 regularization weight for stage 1
    lbda_2d:
      - 0.00001
      - 0.0001
      - 0.001
      - 0.01
      - 0.1
      - 1
      - 10

    # L2 regularization weight for stage 2
    lbda_3d:
      - 0.00001
      - 0.0001
      - 0.001
      - 0.01
      - 0.1
      - 1
      - 10

    # Whether to use bias or not in stage 1
    fit_intercept_2d:
      - True
      - False

    # Whether to use bias or not in stage 2
    fit_intercept_3d:
      - True
      - False


# EVALUATION
evaluation:
