################################################################################
#   CONFIGURATIONS FOR HYPERPARAMETERS TUNING WITH WARPED TWO-STAGE AGGREGATE RIDGE REGRESSION
################################################################################

# DATASET
dataset:
  # Path to main model data .nc file
  path: data/aodisaggregation_emmisions_test_6.3_ACCMIP_200806.06_echam.nc

  # Variables to use as 2D covariates
  2d_covariates:
    - temp2
    - wind10

  # Variables to use as 3D covariates
  3d_covariates:
    - pressure
    - relhum

  # Variable to use as 2D aggregate target
  target: TAU_2D_550nm

  # Variable corresponding to unobserved groundtruth 3D field
  groundtruth: ALFA_AER_533nm


# MODEL SPECIFICATIONS
model:
  # Weights initialization seed
  seed: 42



# TRAINING
training:
  # Number of training epochs
  n_epochs: 15000

  # Learning rate
  lr: 0.1



# GRID SEARCH
search:
  # Number of cross-validation splits to use
  n_splits: 5

  # Search grid
  grid:
    # L2 regularization weight for stage 1
    lbda_2d:
      - 0.0001
      - 0.001
      - 0.01
      - 0.1
      - 1
      - 10

    # L2 regularization weight for stage 2
    lbda_3d:
      - 0.0001
      - 0.001
      - 0.01
      - 0.1
      - 1
      - 10

    # Whether to use bias or not in stage 1
    fit_intercept_2d:
      - True
      - False

    # Whether to use bias or not in stage 2
    fit_intercept_3d:
      - True
      - False

    # Warping transformation
    transform:
      - 'square'
      - 'smooth_abs'


# EVALUATION
evaluation:
