################################################################################
#   CONFIGURATIONS FOR VERTICAL DISAGGREGATION EXPERIMENT WITH MAP GP GAMMA REGRESSION
################################################################################

# DATASET
dataset:
  # Path to main model data .nc file
  path: data/aodisaggregation_emmisions_test_6.3_ACCMIP_200806.06_echam.nc

  # Variables to use as 3D covariates
  3d_covariates:
    - height

  # Variable to use as 2D aggregate target (i.e. AOD)
  target: TAU_2D_550nm

  # Spatially smoothed 2D aggregate target used for rescaling
  smoothed_target: SMOOTH_TAU_2D_550nm

  # Variable corresponding to unobserved groundtruth 3D field (i.e. bext)
  groundtruth: ALFA_AER_533nm



# MODEL SPECIFICATIONS
model:
  # Idealized profile heigthscale parameter -- see notebooks/choose-exponential-height-scale.ipynb
  L: 0.8708489560412566




# EVALUATION
evaluation:
  # Fixed white noise term to make a distribution (not important)
  noise: 0.00000000001

  # bext observation model calibrated scale parameter
  sigma_ext: 2.430

  # Number of test columns (to speed up probabilistic evaluation)
  n_test_samples: 10000

  # Latitude index of slice to plot
  slice_latitude_idx: 20

  # Time index of slice to plot
  slice_time_idx: 0

  # List of variables slices to plot
  slices_covariates:
    - pressure
    - ALFA_AER_533nm

  # Time index of profiles to plot
  profiles_time_idx: 0

  # Number of profils to plot
  n_profiles: 10

  # Random seed used to select calibration profiles
  calibration_seed: 5

  # Random seed to choose profiles
  seed: 5
