################################################################################
#   CONFIGURATIONS FOR VERTICAL DISAGGREGATION EXPERIMENT WITH MAP GP GAMMA REGRESSION
################################################################################

# DATASET
dataset:
  # Path to main model data .nc file
  path: data/aodisaggregation_emmisions_test_6.3_ACCMIP_200806.06_echam.nc

  # Variables to use as 3D covariates
  3d_covariates:
    - pressure_as_normal
    - relhum_as_normal
    # - ALFA_AER_533nm_as_normal

  # Variable to use as 2D aggregate target
  target: TAU_2D_550nm

  # Variable corresponding to unobserved groundtruth 3D field
  groundtruth: ALFA_AER_533nm



# MODEL SPECIFICATIONS
model:
  # Whether to use bias or not
  fit_intercept: True

  # Weights initialization seed
  seed: 42



# TRAINING
training:
  # Number of training epochs
  n_epochs: 32

  # Learning rate
  lr: 0.01

  # Random seed for MC sampling
  seed: 42

  # Number of MC samples
  n_samples: 50



# MAP estimation
MAP:
  # Number of training epochs
  n_epochs: 8

  # Learning rate
  lr: 1



# EVALUATION
evaluation:
  # Latitude index of slice to plot
  slice_latitude_idx: 20

  # Time index of slice to plot
  slice_time_idx: 0

  # List of variables slices to plot
  slices_covariates:
    - pressure
    - relhum
    - ALFA_AER_533nm
    - log_ALFA_AER_533nm
