################################################################################
#   CONFIGURATIONS FOR VERTICAL DISAGGREGATION EXPERIMENT WITH SVGP MODEL
################################################################################

# DATASET
dataset:
  # Path to main model data .nc file
  path: data/aodisaggregation_emmisions_test_6.3_ACCMIP_200806.06_echam.nc

  # Meteorological variables to use as 3D predictors
  3d_covariates:
    - pressure_as_normal
    - st_as_normal
    - relhum_as_normal
    - omega_as_normal
    - height  # only used to initialize inducing points in boundary layer

  # Variable to use as 2D aggregate target (i.e. AOD)
  target: TAU_2D_550nm

  # Spatially smoothed 2D aggregate target used for rescaling
  smoothed_target: SMOOTH_TAU_2D_550nm

  # Variable corresponding to unobserved groundtruth 3D field (i.e. bext)
  groundtruth: ALFA_AER_533nm



# MODEL SPECIFICATIONS
model:
  # Number of inducing points
  n_inducing_points: 200

  # Idealized profile heigthscale parameter -- see notebooks/choose-exponential-height-scale.ipynb
  L: 0.8708489560412566

  # Weights initialization seed
  seed: 42



# TRAINING
training:
  # Number of training epochs
  n_epochs: 2
  # n_epochs: 8

  # Learning rate
  lr: 0.01

  # Random seed for MC sampling
  seed: 42

  # Batch size
  batch_size: 64
  # batch_size: 8




# EVALUATION
evaluation:
  # Size of batches used for inference
  batch_size: 50

  # Number of MC samples used for bext posterior estimation
  n_samples: 1000
  # n_samples: 100

  # bext observation model calibrated scale parameter
  sigma_ext: 2.

  # Number of test columns (to speed up probabilistic evaluation)
  n_test_samples: 10000

  # Latitude index of slice to plot
  slice_latitude_idx: 20

  # Time index of slice to plot
  slice_time_idx: 0

  # List of variables slices to plot
  slices_covariates:
    - pressure
    - st
    - relhum
    - omega

  # Time index of profiles to plot
  profiles_time_idx: 0

  # Number of profils to plot
  n_profiles: 10

  # Random seed used to select calibration profiles
  calibration_seed: 5

  # Random seed to choose profiles
  seed: 5
