################################################################################
#   CONFIGURATIONS FOR VERTICAL DISAGGREGATION EXPERIMENT WITH MAP GP GAMMA REGRESSION
################################################################################

# DATASET
dataset:
  # Path to main model data .nc file
  path: data/aodisaggregation_emmisions_test_6.3_ACCMIP_200806.06_echam.nc

  # Variables to use as 3D covariates
  3d_covariates:
    - pressure_as_normal
    - relhum_as_normal
    # - ALFA_AER_533nm_as_normal
    - height

  # Variable to use as 2D aggregate target
  target: TAU_2D_550nm

  # Variable corresponding to unobserved groundtruth 3D field
  groundtruth: ALFA_AER_533nm



# MODEL SPECIFICATIONS
model:
  # Whether to use bias or not
  fit_intercept: False

  # Number of inducing points
  n_inducing_points: 60

  # Idealized profile lengthscale parameter
  lbda: 1.8

  # Weights initialization seed
  seed: 42



# TRAINING
training:
  # Number of training epochs
  n_epochs: 4

  # Learning rate
  lr: 0.01

  # Random seed for MC sampling
  seed: 42

  # Number of MC samples
  n_samples: 1

  # Batch size
  batch_size: 64




# EVALUATION
evaluation:
  # Size of batches used for inference
  batch_size: 50

  # Number of MC samples used for posterior mean estimation
  n_samples: 1000

  # Latitude index of slice to plot
  slice_latitude_idx: 20

  # Time index of slice to plot
  slice_time_idx: 0

  # List of variables slices to plot
  slices_covariates:
    - pressure
    - relhum
    - ALFA_AER_533nm
    - log_ALFA_AER_533nm

  # Time index of profiles to plot
  profiles_time_idx: 0

  # Number of profils to plot
  n_profiles: 10

  # Random seed to choose profiles
  seed: 5
