################################################################################
#   CONFIGURATIONS FOR VERTICAL DISAGGREGATION EXPERIMENT WITH TWO-STAGE AGGREGATE RIDGE REGRESSION
################################################################################

# DATASET
dataset:
  # Path to main model data .nc file
  path: data/aodisaggregation_emmisions_test_6.3_ACCMIP_200806.06_echam.nc

  # Variables to use as 2D covariates
  2d_covariates:
    - temp2
    - wind10

  # Variables to use as 3D covariates
  3d_covariates:
    - pressure
    - relhum

  # Variable to use as 2D aggregate target
  target: TAU_2D_550nm

  # Variable corresponding to unobserved groundtruth 3D field
  groundtruth: ALFA_AER_533nm


# MODEL SPECIFICATIONS
model:
  # L2 regularization weight for stage 1
  lbda_2d: 0.00001

  # L2 regularization weight for stage 2
  lbda_3d: 0.01

  # Whether to use bias or not in stage 1
  fit_intercept_2d: True

  # Whether to use bias or not in stage 1
  fit_intercept_3d: True


# EVALUATION
evaluation:
  # Latitude index of slice to plot
  slice_latitude_idx: 20

  # Time index of slice to plot
  slice_time_idx: 0

  # List of variables slices to plot
  slices_covariates:
    - pressure
    - relhum
    - ALFA_AER_533nm
    - log_ALFA_AER_533nm
